<Project>
  <PropertyGroup>
    <!-- Folder containing SpaceEngineers.exe -->
    <Bin64>C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64</Bin64>

    <!-- Plugin version -->
    <Version>1.1.1</Version>
    <AssemblyVersion>1.1.1.0</AssemblyVersion>
    <FileVersion>1.1.1.0</FileVersion>
  </PropertyGroup>
</Project>